fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index:
#
#    path: /
#    controller: App\Controller\HomeController::homepage


#homepage:
#    path:       /{_locale}/homepage
#    controller: App\Controller\home\HomeController::homepage
#    requirements:
#        _locale: en|fr|pt